
import {
    STATE_NAMES as DELIVERY_STATES,
} from './delivery'

export enum BOX_STATES {
  IDLE                = "IDLE",
  OFFLINE             = "OFFLINE",
  BLOCKED_BY_DELIVERY = "BLOCKED_BY_DELIVERY",
  OUT_OF_PARTITIONS   = "OUT_OF_PARTITIONS",
}

export enum BOX_OPERATIONS {
  BLOCK_FOR_DELIVERY = "BLOCK_FOR_DELIVERY",
}

export const LOW_BATTERY_THRESHOLD_CENT = 5

export const BLOCKING_DELIVERY_RECIPIENT_STATES = [
    DELIVERY_STATES.PACKAGE_IN_SENDER_BOX,
    DELIVERY_STATES.PACKAGE_WAITING_FOR_DELIVERY,
    DELIVERY_STATES.DELIVERY_ACCEPTED_BY_TRANSPORT_COMPANY,
    DELIVERY_STATES.SENDER_BOX_OPENED_BY_TRANSPORT_COMPANY,
    DELIVERY_STATES.PACKAGE_TAKEOVER_BY_TRANSPORT_COMPANY,
    DELIVERY_STATES.RECIPIENT_BOX_OPENED_BY_TRANSPORT_COMPANY,
    DELIVERY_STATES.PACKAGE_IN_RECIPIENT_BOX,
    DELIVERY_STATES.RECIPIENT_BOX_OPENED_BY_RECIPIENT,
]

export const BLOCKING_DELIVERY_SENDER_STATES = [
    DELIVERY_STATES.READY_FOR_BOX,
    DELIVERY_STATES.PACKAGE_IN_SENDER_BOX,
    DELIVERY_STATES.PACKAGE_WAITING_FOR_DELIVERY,
    DELIVERY_STATES.DELIVERY_ACCEPTED_BY_TRANSPORT_COMPANY,
    DELIVERY_STATES.SENDER_BOX_OPENED_BY_TRANSPORT_COMPANY,
    DELIVERY_STATES.PACKAGE_TAKEOVER_BY_TRANSPORT_COMPANY,
]
