
import {
    DELIVERY_STATE_NAMES,
} from './delivery'

export enum BOX_STATES {
    IDLE                = "IDLE",
    OFFLINE             = "OFFLINE",
    BLOCKED_BY_DELIVERY = "BLOCKED_BY_DELIVERY",
    OUT_OF_PARTITIONS   = "OUT_OF_PARTITIONS",
}

export enum BOX_OPERATIONS {
    BLOCK_FOR_DELIVERY = "BLOCK_FOR_DELIVERY",
}

export const LOW_BATTERY_THRESHOLD_CENT = 5

export const BLOCKING_DELIVERY_RECIPIENT_STATES = [
    DELIVERY_STATE_NAMES.PACKAGE_IN_SENDER_BOX,
    DELIVERY_STATE_NAMES.PACKAGE_WAITING_FOR_DELIVERY,
    DELIVERY_STATE_NAMES.DELIVERY_ACCEPTED_BY_TRANSPORT_COMPANY,
    DELIVERY_STATE_NAMES.SENDER_BOX_OPENED_BY_TRANSPORT_COMPANY,
    DELIVERY_STATE_NAMES.PACKAGE_TAKEOVER_BY_TRANSPORT_COMPANY,
    DELIVERY_STATE_NAMES.RECIPIENT_BOX_OPENED_BY_TRANSPORT_COMPANY,
    DELIVERY_STATE_NAMES.PACKAGE_IN_RECIPIENT_BOX,
    DELIVERY_STATE_NAMES.RECIPIENT_BOX_OPENED_BY_RECIPIENT,
]

export const BLOCKING_DELIVERY_SENDER_STATES = [
    DELIVERY_STATE_NAMES.READY_FOR_BOX,
    DELIVERY_STATE_NAMES.PACKAGE_IN_SENDER_BOX,
    DELIVERY_STATE_NAMES.PACKAGE_WAITING_FOR_DELIVERY,
    DELIVERY_STATE_NAMES.DELIVERY_ACCEPTED_BY_TRANSPORT_COMPANY,
    DELIVERY_STATE_NAMES.SENDER_BOX_OPENED_BY_TRANSPORT_COMPANY,
    DELIVERY_STATE_NAMES.PACKAGE_TAKEOVER_BY_TRANSPORT_COMPANY,
]
