
import * as JavascriptStateMachine from 'javascript-state-machine'

import {
    DELIVERY_STATE_NAMES,
    DELIVERY_TRANSITION_NAME,
} from './constants/delivery'

export const StateMachine = (init) => {
    return new JavascriptStateMachine({
        init,
        transitions: [{
            name: DELIVERY_TRANSITION_NAME.UPDATE_FORM,
            from: DELIVERY_STATE_NAMES.NONE,
            to:   DELIVERY_STATE_NAMES.FORM_IN_PROGRESS,
        }, {
            name: DELIVERY_TRANSITION_NAME.UPDATE_FORM,
            from: DELIVERY_STATE_NAMES.FORM_IN_PROGRESS,
            to:   DELIVERY_STATE_NAMES.FORM_IN_PROGRESS,
        }, {
            name: DELIVERY_TRANSITION_NAME.UPDATE_FORM,
            from: DELIVERY_STATE_NAMES.PAYMENT_IN_PROGRESS,
            to:   DELIVERY_STATE_NAMES.FORM_IN_PROGRESS,
        }, {
            name: DELIVERY_TRANSITION_NAME.DELETED_BY_RECIPIENT_WITHOUT_REFUND,
            from: DELIVERY_STATE_NAMES.FORM_IN_PROGRESS,
            to:   DELIVERY_STATE_NAMES.DELETED_WITHOUT_REFUND,
        }, {
            name: DELIVERY_TRANSITION_NAME.DELETED_BY_RECIPIENT_WITHOUT_REFUND,
            from: DELIVERY_STATE_NAMES.PAYMENT_IN_PROGRESS,
            to:   DELIVERY_STATE_NAMES.DELETED_WITHOUT_REFUND,
        }, {
            name: DELIVERY_TRANSITION_NAME.PAYMENT_ATTEMPT,
            from: DELIVERY_STATE_NAMES.FORM_IN_PROGRESS,
            to:   DELIVERY_STATE_NAMES.PAYMENT_IN_PROGRESS,
        }, {
            name: DELIVERY_TRANSITION_NAME.PAYMENT_ATTEMPT,
            from: DELIVERY_STATE_NAMES.PAYMENT_IN_PROGRESS,
            to:   DELIVERY_STATE_NAMES.PAYMENT_IN_PROGRESS,
        }, {
            name: DELIVERY_TRANSITION_NAME.SUCCESSFUL_PAYMENT,
            from: DELIVERY_STATE_NAMES.PAYMENT_IN_PROGRESS,
            to:   DELIVERY_STATE_NAMES.PAID,
        }, {
            name: DELIVERY_TRANSITION_NAME.PACKAGE_TAGGED,
            from: DELIVERY_STATE_NAMES.PAID,
            to:   DELIVERY_STATE_NAMES.READY_FOR_BOX,
        }, {
            name: DELIVERY_TRANSITION_NAME.PACKAGE_TAGGED,
            from: DELIVERY_STATE_NAMES.READY_FOR_BOX,
            to:   DELIVERY_STATE_NAMES.READY_FOR_BOX,
        }, {
            name: DELIVERY_TRANSITION_NAME.SENDER_OPENS_BOX,
            from: DELIVERY_STATE_NAMES.READY_FOR_BOX,
            to:   DELIVERY_STATE_NAMES.PACKAGE_IN_SENDER_BOX,
        }, {
            name: DELIVERY_TRANSITION_NAME.SENDER_OPENS_BOX,
            from: DELIVERY_STATE_NAMES.PACKAGE_IN_SENDER_BOX,
            to:   DELIVERY_STATE_NAMES.PACKAGE_IN_SENDER_BOX,
        }, {
            name: DELIVERY_TRANSITION_NAME.SENDER_CONFIRMS_DELIVERY,
            from: DELIVERY_STATE_NAMES.PACKAGE_IN_SENDER_BOX,
            to:   DELIVERY_STATE_NAMES.PACKAGE_WAITING_FOR_DELIVERY,
        }, {
            name: DELIVERY_TRANSITION_NAME.SENDER_CONFIRMS_DELIVERY,
            from: DELIVERY_STATE_NAMES.READY_FOR_BOX,
            to:   DELIVERY_STATE_NAMES.PACKAGE_WAITING_FOR_DELIVERY,
        }, {
            name: DELIVERY_TRANSITION_NAME.TRANSPORT_COMPANY_ACCEPTS,
            from: DELIVERY_STATE_NAMES.PACKAGE_WAITING_FOR_DELIVERY,
            to:   DELIVERY_STATE_NAMES.DELIVERY_ACCEPTED_BY_TRANSPORT_COMPANY,
        }, {
            name: DELIVERY_TRANSITION_NAME.TRANSPORT_COMPANY_ACCEPTS,
            from: DELIVERY_STATE_NAMES.DELIVERY_ACCEPTED_BY_TRANSPORT_COMPANY,
            to:   DELIVERY_STATE_NAMES.DELIVERY_ACCEPTED_BY_TRANSPORT_COMPANY,
        }, {
            name: DELIVERY_TRANSITION_NAME.TRANSPORT_COMPANY_OPENS_SENDER_BOX,
            from: DELIVERY_STATE_NAMES.DELIVERY_ACCEPTED_BY_TRANSPORT_COMPANY,
            to:   DELIVERY_STATE_NAMES.SENDER_BOX_OPENED_BY_TRANSPORT_COMPANY,
        }, {
            name: DELIVERY_TRANSITION_NAME.TRANSPORT_COMPANY_CONFIRMS_PACKAGE_TAKEOVER,
            from: DELIVERY_STATE_NAMES.SENDER_BOX_OPENED_BY_TRANSPORT_COMPANY,
            to:   DELIVERY_STATE_NAMES.PACKAGE_TAKEOVER_BY_TRANSPORT_COMPANY,
        }, {
            name: DELIVERY_TRANSITION_NAME.TRANSPORT_COMPANY_CONFIRMS_PACKAGE_TAKEOVER,
            from: DELIVERY_STATE_NAMES.DELIVERY_ACCEPTED_BY_TRANSPORT_COMPANY,
            to:   DELIVERY_STATE_NAMES.PACKAGE_TAKEOVER_BY_TRANSPORT_COMPANY,
        }, {
            name: DELIVERY_TRANSITION_NAME.TRANSPORT_COMPANY_OPENS_RECIPIENT_BOX,
            from: DELIVERY_STATE_NAMES.PACKAGE_TAKEOVER_BY_TRANSPORT_COMPANY,
            to:   DELIVERY_STATE_NAMES.RECIPIENT_BOX_OPENED_BY_TRANSPORT_COMPANY,
        }, {
            name: DELIVERY_TRANSITION_NAME.TRANSPORT_COMPANY_CONFIRMS_PACKAGE_DELIVERED,
            from: DELIVERY_STATE_NAMES.RECIPIENT_BOX_OPENED_BY_TRANSPORT_COMPANY,
            to:   DELIVERY_STATE_NAMES.PACKAGE_IN_RECIPIENT_BOX,
        }, {
            name: DELIVERY_TRANSITION_NAME.TRANSPORT_COMPANY_CONFIRMS_PACKAGE_DELIVERED,
            from: DELIVERY_STATE_NAMES.PACKAGE_TAKEOVER_BY_TRANSPORT_COMPANY,
            to:   DELIVERY_STATE_NAMES.PACKAGE_IN_RECIPIENT_BOX,
        }, {
            name: DELIVERY_TRANSITION_NAME.RECIPIENT_OPENS_BOX,
            from: DELIVERY_STATE_NAMES.PACKAGE_IN_RECIPIENT_BOX,
            to:   DELIVERY_STATE_NAMES.RECIPIENT_BOX_OPENED_BY_RECIPIENT,
        }, {
            name: DELIVERY_TRANSITION_NAME.RECIPIENT_OPENS_BOX,
            from: DELIVERY_STATE_NAMES.RECIPIENT_BOX_OPENED_BY_RECIPIENT,
            to:   DELIVERY_STATE_NAMES.RECIPIENT_BOX_OPENED_BY_RECIPIENT,
        }, {
            name: DELIVERY_TRANSITION_NAME.RECIPIENT_CONFIRMS_DELIVERY,
            from: DELIVERY_STATE_NAMES.RECIPIENT_BOX_OPENED_BY_RECIPIENT,
            to:   DELIVERY_STATE_NAMES.PACKAGE_CONFIRMED_BY_RECIPIENT,
        }, {
            name: DELIVERY_TRANSITION_NAME.RECIPIENT_CONFIRMS_DELIVERY,
            from: DELIVERY_STATE_NAMES.PACKAGE_IN_RECIPIENT_BOX,
            to:   DELIVERY_STATE_NAMES.PACKAGE_CONFIRMED_BY_RECIPIENT,
        }],
    })
}
